const jugadoresDB = [
  { nombre: "Abraham, Francisco Jose", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Acosta, Marcos Santiago", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Adorati, Santiago", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Agüero, Gabriel Valentin", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Allende, Claudio Damian", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Álvarez Vivian, Bautista", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Amado, Lorenzo", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Arias nieto, Kevin Gabriel", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Ariza manzanelli, Ian Zair", pie: "Izquierdo", posicion: "Enganche" },
  { nombre: "Arrascaeta, Maximo Martin", pie: "Izquierdo", posicion: "Volante Mixto" },
  { nombre: "Badiali, Constantino", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Barreiro Valdez, Agustin", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Bazan, Santiago Andres", pie: "Izquierdo", posicion: "Defensor Central" },
  { nombre: "Bellio, Uriel Maximiliano", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Bianco Petrakovsky, Faustino", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Biani Rico, Jeremías Iván", pie: "Izquierdo", posicion: "Extremo" },
  { nombre: "Biani Rico, Benjamin Ezequiel", pie: "Izquierdo", posicion: "Volante Central" },
  { nombre: "Blangino, Thiago Benjamin", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Bono, Agustin", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Boasi Colombo, Guillermo Alejandro", pie: "", posicion: "" },
  { nombre: "Boscatto, Bautista", pie: "Izquierdo", posicion: "Volante Central" },
  { nombre: "Bracamonte, Genaro", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Brian Hails, Ivo", pie: "Derecho", posicion: "Segunda Punta" },
  { nombre: "Brustolin, Mateo", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Bustos Llorens, Alejo", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Calero, Francisco", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Caligaris, Valentino", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Caprari, Lucca", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Carmona, Matteo", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Carrizo Rio, tiago ignacio", pie: "Izquierdo", posicion: "Volante Mixto" },
  { nombre: "Casas, Mateo Jesús Santino", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Casas, Francisco Cesar", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Castagno, Pedro", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Castelvetri, Genaro", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Castelvetri, Santino", pie: "Izquierdo", posicion: "Volante Mixto" },
  { nombre: "Castillo, Santino nicolas", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Caciorgna, Agustin", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Ceballos, Enzo", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Ceballos, Mateo Valentín", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Chacarelli, Franco Ezequiel", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Chavero Francia, Fausto Nicolás", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Chavez Silva, Santiago Nicolas", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Chaparro, Ulises Nahuel", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Chittaro, Valentin", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Cheetham Tarditto, Fermin", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Christe, Tomas", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Cortes, Thiago", pie: "Derecho", posicion: "Enganche" },
  { nombre: "Corti, Valentin", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Cornaglia Curto, Joaquin", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Cruz, Ivo Francisco", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Cuello, Jorge Ismael", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Curletto, Santino", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Del Bianco, Joaquin Natanael", pie: "Derecho", posicion: "Delantero Centro" },
    { nombre: "Di Camillo, Tomás", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Dietz, Tomas Sebastian", pie: "Izquierdo", posicion: "Extremo" },
  { nombre: "Dominguez, Lucas Ezequiel", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Echenique Flores, Dylan Thiago", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Elero, Simon", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Espindola, Mateo Valentin", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Faggioli, Ignacio Nahir", pie: "Izquierdo", posicion: "Volante Central" },
  { nombre: "Farias Murua, Jeremias Francisco", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Farias, Ulises emanuel", pie: "Izquierdo", posicion: "Volante Mixto" },
  { nombre: "Falcon, Agustin", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Flandes, Joaquin", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Fleurilus, Amy", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Fiori, Santino", pie: "Izquierdo", posicion: "Enganche" },
  { nombre: "Firpo, Benjamín Alejandro", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Flores Reynoso, Roman Leonel", pie: "Izquierdo", posicion: "Defensor Central" },
  { nombre: "Frasnelli, Raúl Fernando", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Fulgenzi Muñoz, Francisco Ignacio", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Galindez Mauro, Cesar Michel", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Galindez Mauro, César Michel", pie: "Izquierdo", posicion: "Enganche" },
  { nombre: "Galetto, Benjamin", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Galli, Santiago", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Garade Flores, Cruz Facundo", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Garay, Kevin Carlos Leonel", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Garcia, Tomas gabriel", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Garnica, Nicolas", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Garrido, Nicolas", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Gaviglio, Santiago Javier", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Gaona, Tiago Ezequiel", pie: "Derecho", posicion: "Enganche" },
  { nombre: "Gatti, Santino Ariel", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Gimenez, Cristiano Gastón", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Goncalvez, tiago ezequiel", pie: "Izquierdo", posicion: "Arquero" },
  { nombre: "Gonzalez Jaca, Lautaro", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Gonzalez, Lucio", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Gonzalez, Ramon Jacinto Ramiro", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Gonzalez, Tomas Andres", pie: "Izquierdo", posicion: "Defensor Central" },
  { nombre: "Gonzalez, Tomas Valentino", pie: "Derecho", posicion: "Enganche" },
  { nombre: "Grosso, Ian", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Griguol Rosso, Agustin", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Gutierrez, Lautaro Ismael", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Gutierrez, Luka Pedro", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Heredia, Santino ismael", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Hernandez, Nahuel", pie: "Izquierdo", posicion: "Extremo" },
  { nombre: "Herrera, Juan Cruz", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Jackson, Thomas", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Jacob Sanchez, Santiago Matias", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Jaime Re, Santiago", pie: "Izquierdo", posicion: "Defensor Central" },
  { nombre: "Jerez, Thiago", pie: "Izquierdo", posicion: "Defensor Central" },
  { nombre: "Jimenez, Lionel Alejandro", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Juncos Ceballos, Dylan Farid", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Kañesky, Facundo Leonel", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Kippes, Genaro", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "La Licata, Bautista", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "La Licata, Tomas", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Lardone Leiva, Samuel", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Lencina, Maximo Jesus", pie: "Izquierdo", posicion: "Extremo" },
  { nombre: "Lecler, Alan", pie: "Izquierdo", posicion: "Extremo" },
  { nombre: "Leiva, Gustavo Gabriel", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Leyria Pierobon, Francisco", pie: "Derecho", posicion: "Arquero" },
  { nombre: "López, Lautaro José", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Lopez, Tiago Nicolas", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Lopez Mendez, Joaquin", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Lovaiza, Juan Cruz", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Ludueña, Said Silvano", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Lucci, Yuthiel Leonel", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Luna, Thiago Valentin", pie: "Izquierdo", posicion: "Volante Mixto" },
    { nombre: "Machado, Dylan nahuel", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Maidana Nuñez, Federico Ignacio", pie: "Derecho", posicion: "Enganche" },
  { nombre: "Madriaga, Lionel Santiago", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Manzanares, Ignacio Jose", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Manzano, Thiago Gabriel", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Mastrocola, Alexis caleb", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Martinez, Gastón David", pie: "Izquierdo", posicion: "Volante Central" },
  { nombre: "Martinez Deusa, Lukas Exequiel", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Martino Domínguez, Thiago Simon", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Mecia Aponte, Raynier Alejandro", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Melano, Agustín Nicolás", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Mena Figueroa, Benjamin de Dios", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Menseguez longo, máximo", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Mendieta, Fabricio Ezequiel", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Miño, Juan Pablo", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Miño, Santiago Omar", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Molina Percello, Javier Nicolas", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Monserrat, Santiago", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Montenegro, Ismael", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Montoya, Nicolas Gabriel", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Monzon, Leandro Gabriel", pie: "Izquierdo", posicion: "Enganche" },
  { nombre: "Moreira, Eneas nael", pie: "Izquierdo", posicion: "Extremo" },
  { nombre: "Moyano, Nazareno", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Muriado, Lucas", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Muñoz, Leandro Maria", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Muñoz, Santino", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Navarro Olivera, Luka Lautaro", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Nazario, Juan Pablo", pie: "Derecho", posicion: "Enganche" },
  { nombre: "Nieto, facundo ulises", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Nieto, Francisco Benjamin", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Nuñez, Julian David", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Ocampo, Alvaro", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Occhipinti, Salvador", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Olariaga, Agustín", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Oliveto, Agustín", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Oliva Jacob, Mateo", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Olivera, Gabriel Alejandro", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Olmedo, Joaquin Ezequiel", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Olmedo, Kevin tahiel", pie: "Izquierdo", posicion: "Volante Mixto" },
  { nombre: "Ortega, Álvaro Martin", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Orellano, Bautista", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Oscare, Santiago", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Ozuna, Matheo Gadiel", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Paez, Benjamin Nicolas", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Paez, Gonzalo", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Pacher Cantet, Maxi", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Palma Fuentes, Lautaro Nicolas", pie: "Izquierdo", posicion: "Defensor Central" },
  { nombre: "Paredes Buryaile, Ivo", pie: "Derecho", posicion: "Segunda Punta" },
  { nombre: "Parnisari, Hugo Laureano", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Passarelli Martino, Lorenzo", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Peano, Santiago", pie: "Derecho", posicion: "Enganche" },
  { nombre: "Pedrozo, Mateo Benjamin", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Pereyra Ceballos, Francisco Joel", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Pérez, Lucio", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Pivetta, Felipe", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Ponce, Alexis Exequiel", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Pucheta, Tobias Gonzalo", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Quintero, Lorenzo Damian", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Ramallo, Franco Andrés", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Razzeto, Francisco", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Regali, Danilo Diego David", pie: "Izquierdo", posicion: "Defensor Central" },
  { nombre: "Rimondotto, Lorenzo", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Rios, Bruno Mateo Rios", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Rios, brandon facundo", pie: "Izquierdo", posicion: "Extremo" },
  { nombre: "Rios, Ramiro Agustin", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Robacio Oviedo, Thiago", pie: "Izquierdo", posicion: "Defensor Central" },
  { nombre: "Rodriguez Grisanti, Nicolas", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Rodríguez, Matias Leonel", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Rodríguez Olmedo, Galo Román", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Romero, Braian", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Rosellini, Bautista", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Rueda, Lautaro Joaquín", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Rubio, Benjamín Nicolás", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Rustichelli, Luca", pie: "Izquierdo", posicion: "Volante Mixto" },
  { nombre: "Saccani, Valentin", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Sánchez, Fabricio Angel Tomás", pie: "Izquierdo", posicion: "Enganche" },
  { nombre: "Sánchez, Tomas Mauricio", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Sanchez Capretta, Juan Ignacio", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Sánchez Ravenna, Jeremías", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Salort, Martín", pie: "Derecho", posicion: "Volante Mixto" },
    { nombre: "Sepulveda Gil, Daniel Agustín", pie: "Izquierdo", posicion: "Defensor Central" },
  { nombre: "Signoretta, Luciano Benjamín", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Silva Chanquia, Thiago Javier", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Silveira, Franco david", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Simons Peña, Roberto Sayyed", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Solazzo, Rial, Gaspar", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Suárez, Kevin Rubén", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Suárez, Lautaro Andre", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Tabarez, Thiago fernando", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Tapia, Dylan Emmanuel", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Tapia Carpio, Benjamin", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Tapia Gianini, Román Ignacio", pie: "Izquierdo", posicion: "Defensor Central" },
  { nombre: "Thiago Ezequiel, Gaona", pie: "Derecho", posicion: "Enganche" },
  { nombre: "Tisera, Octavio", pie: "Izquierdo", posicion: "Defensor Central" },
  { nombre: "Tobares, Leonel Ezequiel", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Togachinsco, Ramiro Valentin", pie: "Derecho", posicion: "Segunda Punta" },
  { nombre: "Torielli, Lautaro Nicolas", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Turletti, Juan Andres", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Uriona Devetter, Martino", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Utrera, Santiago Tomas", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Valdez Ruiz, Benjamin Misahel", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Vera, Jovany sebastian", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Vergara Escobar, Joaquín Hugo", pie: "Izquierdo", posicion: "Defensor Central" },
  { nombre: "Velazco, Lucio Alejandro", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Villalba, Luciano Benjamin", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Villarroel, Maximo", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Wendel, Tiziano", pie: "Izquierdo", posicion: "" },
  { nombre: "Zapata, Leonidas Catriel", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Zarabozo, Osvaldo Nicolas", pie: "Izquierdo", posicion: "Volante Central" },
  { nombre: "Zarate Randon, Valentin", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Zelarayan, Alexis", pie: "Izquierdo", posicion: "Arquero" },

  // BLOQUE EXTRA: nombres repetidos que consolidé
  { nombre: "Bévolo, Benjamín", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Elero, Simon", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Flores Reynoso, Roman Leonel", pie: "Izquierdo", posicion: "Defensor Central" },
  { nombre: "Galetto, Benjamin", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Garnica, Nicolas", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Gaviglio, Santiago Javier", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Gutierrez, Luka Pedro", pie: "Derecho", posicion: "Extremo" },
  { nombre: "La Licata, Bautista", pie: "Ambos", posicion: "Volante Central" },
  { nombre: "Licari, Nicolas", pie: "Izquierdo", posicion: "Segunda Punta" },
  { nombre: "Machado, Dylan nahuel", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Mecia Aponte, Raynier Alejandro", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Montoya, Nicolas Gabriel", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Muñoz, Leandro Maria", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Oliveto, Agustín", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Pereyra Ceballos, Francisco Joel", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Saccani, Valentin", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Sánchez, Fabricio Angel Tomás", pie: "Izquierdo", posicion: "Enganche" },
  { nombre: "Signoretta, Luciano Benjamín", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Suárez, Lautaro Andre", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Uriona Devetter, Martino", pie: "Derecho", posicion: "Delantero Centro" },
    // BLOQUE CONTINUA
  { nombre: "Villa, Matias Maximiliano", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Villarruel, Santiago", pie: "Izquierdo", posicion: "Defensor Central" },

  // BLOQUE FINAL COMPLEMENTARIO – ORDENADO Y CONSOLIDADO
  { nombre: "Andrada, Fabricio Javier", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Aleuy, Lautaro Benjamín", pie: "Derecho", posicion: "Enganche" },
  { nombre: "Bono, Agustin", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Boscatto, Bautista", pie: "Izquierdo", posicion: "Volante Central" },
  { nombre: "Caligaris, Valentino", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Carrizo Rio, tiago ignacio", pie: "Izquierdo", posicion: "Volante Mixto" },
  { nombre: "Castagno, Pedro", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Castillo, Santino nicolas", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Ceballos, Enzo", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Charras, Thiago", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Christe, Tomas", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Cruz, Ivo Francisco", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Dominguez, Lucas Ezequiel", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Elero, Simon", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Espindola, Mateo Valentin", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Ferreyra, Benjamin", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Gonzalez, Lucio", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Griguol Rosso, Agustin", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Grosso, Ian", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Herrera, Juan Cruz", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Jimenez, Lionel Alejandro", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Kippes, Genaro", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Lencina, Maximo Jesus", pie: "Izquierdo", posicion: "Extremo" },
  { nombre: "Leyria Pierobon, Francisco", pie: "Derecho", posicion: "Arquero" },
  { nombre: "López, Lautaro José", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Lovaiza, Juan Cruz", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Lucci, Yuthiel Leonel", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Manzanares, Ignacio Jose", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Martino Domínguez, Thiago Simon", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Melano, Agustín Nicolás", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Miño, Juan Pablo", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Molina Percello, Javier Nicolas", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Montenegro, Ismael", pie: "Derecho", posicion: "Volante Central" },
  { nombre: "Moyano, Nazareno", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Muñoz, Santino", pie: "Derecho", posicion: "Lateral Derecho" },
  { nombre: "Nazario, Juan Pablo", pie: "Derecho", posicion: "Enganche" },
  { nombre: "Nieto, Francisco Benjamin", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Nuñez, Julian David", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Occhipinti, Salvador", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Ortega, Álvaro Martin", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Paredes Buryaile, Ivo", pie: "Derecho", posicion: "Segunda Punta" },
  { nombre: "Passarelli Martino, Lorenzo", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Pivetta, Felipe", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Pucheta, Tobias Gonzalo", pie: "Izquierdo", posicion: "Lateral Izquierdo" },
  { nombre: "Quintero, Lorenzo Damian", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Rimondotto, Lorenzo", pie: "Derecho", posicion: "Delantero Centro" },
  { nombre: "Robacio Oviedo, Thiago", pie: "Izquierdo", posicion: "Defensor Central" },
  { nombre: "Ríos, Ramiro Agustin", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Rueda, Lautaro Joaquín", pie: "Derecho", posicion: "Defensor Central" },
  { nombre: "Rustichelli, Luca", pie: "Izquierdo", posicion: "Volante Mixto" },
  { nombre: "Salort, Martín", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Sánchez Ravenna, Jeremías", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Sánchez, Fabricio Angel Tomás", pie: "Izquierdo", posicion: "Enganche" },
  { nombre: "Signoretta, Luciano Benjamín", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Solazzo, Rial, Gaspar", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Suárez, Kevin Rubén", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Tapia Carpio, Benjamin", pie: "Derecho", posicion: "Extremo" },
  { nombre: "Thiago Ezequiel, Gaona", pie: "Derecho", posicion: "Enganche" },
  { nombre: "Valdez Ruiz, Benjamin Misahel", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Vera, Jovany sebastian", pie: "Derecho", posicion: "Volante Mixto" },
  { nombre: "Villarroel, Maximo", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Zapata, Leonidas Catriel", pie: "Derecho", posicion: "Arquero" },
  { nombre: "Zarate Randon, Valentin", pie: "Derecho", posicion: "Defensor Central" }
    // ==========================
  //  CIERRE DEL LISTADO
  // ==========================
];
